/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#000000",
        "surface-dim": "#000000",
        "surface-bright": "#2a303a",
        "surface-container-lowest": "#0e1013",
        "surface-container-low": "#16191f",
        "surface-container": "#1c2026",
        "surface-container-high": "#232830",
        "surface-container-highest": "#2a303a",
        "on-surface": "#e8eaed",
        "on-surface-variant": "#9aa0a6",
        "inverse-surface": "#e8eaed",
        "inverse-on-surface": "#202124",
        "outline": "#54595d",
        "outline-variant": "#3a3d40",
        "surface-tint": "#8ab4f8",
        "primary": "#8ab4f8",
        "on-primary": "#000000",
        "primary-container": "#3366cc",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#3366cc",
        "secondary": "#54595d",
        "on-secondary": "#ffffff",
        "secondary-container": "#3a3d40",
        "on-secondary-container": "#e8eaed",
        "tertiary": "#fee77e",
        "on-tertiary": "#000000",
        "tertiary-container": "#c7b34b",
        "on-tertiary-container": "#000000",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#8ab4f8",
        "primary-fixed-dim": "#3366cc",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#1a3366",
        "secondary-fixed": "#e8eaed",
        "secondary-fixed-dim": "#9aa0a6",
        "on-secondary-fixed": "#000000",
        "on-secondary-fixed-variant": "#202124",
        "tertiary-fixed": "#fee77e",
        "tertiary-fixed-dim": "#c7b34b",
        "on-tertiary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#4a421b",
        "background": "#000000",
        "on-background": "#e8eaed",
        "surface-variant": "#2a303a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "5rem",
        "gutter": "1.5rem",
        "grid-margin": "2rem",
        "component-padding": "1rem"
      },
      fontFamily: {
        "label-mono": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Bebas Neue", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-accent": ["Playfair Display", "serif"],
        "display-xl": ["Bebas Neue", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "display-lg": ["Bebas Neue", "sans-serif"]
      },
      fontSize: {
        "label-mono": ["12px", { "lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "500" }],
        "display-lg-mobile": ["48px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-accent": ["80px", { "lineHeight": "72px", "fontWeight": "400" }],
        "display-xl": ["120px", { "lineHeight": "100px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["80px", { "lineHeight": "72px", "letterSpacing": "-0.03em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
