/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#ad897e",
        "secondary-fixed": "#e4e2e1",
        "secondary": "#c8c6c5",
        "surface-variant": "#353534",
        "tertiary-fixed": "#ffdcbf",
        "inverse-on-surface": "#313030",
        "surface": "#000000",
        "inverse-primary": "#ae3200",
        "on-secondary-container": "#b6b5b4",
        "surface-dim": "#000000",
        "on-error": "#690005",
        "tertiary": "#ffdcbf",
        "on-primary-fixed": "#3a0b00",
        "tertiary-fixed-dim": "#ffb874",
        "on-secondary-fixed-variant": "#474746",
        "primary-fixed": "#ff4d00",
        "on-tertiary": "#4b2800",
        "on-surface": "#e5e2e1",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed-variant": "#6a3b00",
        "surface-container-highest": "#353534",
        "on-primary": "#5e1700",
        "surface-bright": "#3a3939",
        "surface-tint": "#ff4d00",
        "on-primary-container": "#521300",
        "on-tertiary-fixed": "#2d1600",
        "surface-container-high": "#2a2a2a",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#ff571a",
        "tertiary-container": "#d47b00",
        "error-container": "#93000a",
        "surface-container-low": "#0a0a0a",
        "on-surface-variant": "#e6beb2",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#852400",
        "primary-fixed-dim": "#00e380",
        "on-secondary": "#303030",
        "surface-container": "#201f1f",
        "secondary-fixed-dim": "#c8c6c5",
        "background": "#000000",
        "secondary-container": "#474746",
        "on-background": "#e5e2e1",
        "outline-variant": "#5c4037",
        "on-secondary-fixed": "#191c1b",
        "on-tertiary-container": "#412200",
        "primary": "#ff4d00",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "5rem",
        "gutter": "1.5rem",
        "grid-margin": "2rem",
        "component-padding": "1rem"
      },
      fontFamily: {
        "label-mono": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Bebas Neue", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-accent": ["Playfair Display", "serif"],
        "display-xl": ["Bebas Neue", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "display-lg": ["Bebas Neue", "sans-serif"]
      },
      fontSize: {
        "label-mono": ["12px", { "lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "500" }],
        "display-lg-mobile": ["48px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-accent": ["80px", { "lineHeight": "72px", "fontWeight": "400" }],
        "display-xl": ["120px", { "lineHeight": "100px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["80px", { "lineHeight": "72px", "letterSpacing": "-0.03em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
